version: '3.8'
services:
  # Init container to install Lua modules
  kong-init:
    image: kong:3.4
    container_name: kong-init
    user: root
    volumes:
      - lua_modules:/usr/local/share/lua/5.1
      - lua_rocks:/usr/local/lib/luarocks
    command: >
      sh -c "
        echo 'Installing dependencies...' &&
        apk add --no-cache git gcc musl-dev make &&
        luarocks install oasvalidator &&
        echo 'Installation complete' &&
        chown -R kong:kong /usr/local/share/lua/5.1 /usr/local/lib/luarocks
      "
    restart: "no"

  kong:
    image: kong:3.4
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PLUGINS: bundled,hello-world,request-logger
      KONG_LUA_PACKAGE_PATH: /kong/plugins/?.lua;/kong/plugins/?/init.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;;
      KONG_LOG_LEVEL: info
    ports:
      - "8000:8000"   # Proxy port
      - "8001:8001"   # Admin API port
      - "8443:8443"   # Proxy SSL port
      - "8444:8444"   # Admin API SSL port
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml:ro
      - ./plugins:/kong/plugins:ro
      - lua_modules:/usr/local/share/lua/5.1:ro
      - lua_rocks:/usr/local/lib/luarocks:ro
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    depends_on:
      - kong-init
      - go-server

  # Simple Go server
  go-server:
    build: .
    container_name: go-simple-server
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  lua_modules:
  lua_rocks:
