version: '3.8'
services:
  kong:
    build:
      context: .
      dockerfile: Dockerfile.kong
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PLUGINS: bundled,hello-world,request-logger
      KONG_LUA_PACKAGE_PATH: /kong/plugins/?.lua;/kong/plugins/?/init.lua;;
      KONG_LOG_LEVEL: info
    ports:
      - "8000:8000"   # Proxy port
      - "8001:8001"   # Admin API port
      - "8443:8443"   # Proxy SSL port
      - "8444:8444"   # Admin API SSL port
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml:ro
      - ./plugins:/kong/plugins:ro
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    depends_on:
      - go-server

  # Simple Go server
  go-server:
    build: .
    container_name: go-simple-server
    ports:
      - "8080:8080"
    restart: unless-stopped
